### ISSUE TITLE
Space missing after \fk in Ezekiel 28:3

### ISSUE THREAD

**Issue by DavidHaslam** [BeTheLight/ENG-B-CPDV2009-pd-PSFM#16]
Currently this reads:
```
\v 3 Behold, you are wiser than Daniel; no secret is concealed from you.\f + \fr 28:3 \fkYou are wiser than Daniel: \ft Viz., in thy own conceit. The wisdom of Daniel was so much celebrated in his days, that it became a proverb amongst the Chaldeans, when any one would express an extraordinary wisdom, to say he was as wise as Daniel.\fl (Challoner)\f*
```
Please insert a space after the `\fk` tag.

_No sniggering at the back of the class!_

**Comment by DavidHaslam** [comment]
The attached text delimited text file provides the **USFM tag statistics** for the concatenated 73 Bible books, excluding the files for the other material.

[merged.usfm.tags.count.usfm.txt](https://github.com/BeTheLight/ENG-B-CPDV2009-pd-PSFM/files/2653997/merged.usfm.tags.count.usfm.txt)

This analysis shows there are few other unexpected or malformed tags.
```
00002	\c0	\c0
00001	\fkYou	\fkYou
00001	\imt6	\imt6
00073	\mte9	\mte9
00055	\q0	\q0
00073	\toc4	\toc4
```
`\toc4` is new to me, so it's possible my own list of tag descriptions requires further editing.

**Comment by DavidHaslam** [comment]
The 2 instances of spurious tag `\c0` are in **LAM**entations! They should simply be removed.

**Comment by DavidHaslam** [comment]
The poetry tag `\q0 ` is probably a typo for `\q ` which is equivalent to `\q1 `.

**Comment by cmahte** [comment]
\toc4 is the number of chapters in the book.

This table of contents entry appears in many works, including the
Authorized Version of 1611. While it is possible to derive this, when extra
or missing chapters are present (as in the CPDV), it is important to
understand if the extra/missing chapters belong in the sum on the TOC.

(In CPDV, Sirach and Lamentations both have 'canonical' verses before the
chapter 1 marker. I mark these as an extra chapter (which has precedent in
USFM. However, the recommendation from ICAP is to shift EVERY chapter up
one, and use \cp to correct. the number. That is, prologue verses are in \c
1 \cp 0, and chapter 1 verses are in \c2 \cp1, etc. This creates a
nightmare for various outputs that don't support \cp to have priority over
\c. They are also clear that their versifications ignore canonical
prologues, including directives in Psalms. Including \c 0 is simpler and
causes fewer issues. ICAP confirms that \c 0 is not against the
specification but breaks ParaTExt.  No rule against it, but it won't work
in practice.

For the Sword Module, in both places, Cyrille is marking the verses with
\va  tags instead of \v tags, and the converter seems to function
properly.)

**Comment by DavidHaslam** [comment]
The single occurrence of `\imt6` is probably a typo for `\imt4`

It's found in this line for **The Book of Esther**.
```
\imt6 Verse numbering compared: Clementine to CPDV
```

However, it's notable that there are no instances of `\imt1` `\imt2` `\imt3` so why start at level 4 ?

**Comment by DavidHaslam** [comment]
I've just emailed Jeff Klassen to enquire about `\toc4 `.

**Comment by DavidHaslam** [comment]
Currently, LAM has this, with both `\c0` and `\c 0` present.
```
\c0
\c 0
\cl Lamentations Prologue
\im In these JEREMIAH laments in a most pathetical manner the miseries of his people, and the destruction of JERUSALEM and the temple, in Hebrew verses, beginning with different letters according to the order of the Hebrew alphabet.
\c0
\v 1 And it happened that, after Israel was driven into captivity, and Jerusalem was deserted,\f + \fr P:1 \ft The Prologue to Lamentations is sacred and canonical, inspired and infallible, just like the rest of the book. The Council of Trent infallibly declared that the Latin Vulgate Bible, with all its parts, is sacred and canonical. The Latin Vulgate Bible includes a Prologue for Lamentations. Therefore, the Prologue is sacred and canonical.\fl (Conte)\f*\f + \fr 0:1 \fk And it came to pass, etc: \ft This preface was not written by Jeremiah, but was added by the seventy interpreters, to give the reader to understand upon what occasion the Lamentations were published.\fl (Challoner)\f*
\v 2 the prophet Jeremiah sat weeping, and he wailed this lamentation in Jerusalem.
\v 3 And sighing with a bitter soul, and mourning, he said:
\c 1
```

**Comment by cmahte** [comment]
FYI: I'm currently dormant on CPDV.  According to the status page, I still
plan to add cross references from Haydock or Challoner (memory suggests
Haydock, but there's an excel file somewhere with a firm answer.) I'm also
planning to add phrase by phrase line endings in several poetic books. Both
of these steps involve mass search/replace operations, after which a full
set of checks will again be required. (**)

Although everything David has found is valid.  I don't plan to seriously
return to the CPDV until after I've published the 1911 Bible, unless a real
demand for it is established. My current free time remains elsewhere
(AV1911, with it's related AV1811 Cambridge paragraph Bible, AV1711 modern
spelling/orthography, and AV1611 original texts, and possibly the
Conservapedia New Testament.) And all of these works are English, and I
really need to keep my complex script skills honed, so likely I'll seek an
Arabic script work to work on after AV1911.

Cyrille is publishing the CPDV for Sword. Maybe these checks should belong
on his gitlab project? I don't know if it's public, but if he can share it,
I'd benefit from his work.

(**) - The poetic line endings turned out to require manual editing, so
this project sits waiting a huge time commitment of a month or more, then
verification/validation reading after that. The poetic books need line
endings marked in the CPDV where the phrases occur in the Challoner, or in
a similar way to some public work based on the Challoner. My attempts to
automate this based on existing punctuation, word length, capitalization,
etc. are substandard (compare Psalms 1-20 to Psalms 90-150, There are 3
different methods of introducing line endings in the current Psalms,
roughly 1-20, 21-90, and 90-150. 1-20 was manually edited. some went
quickly some were slow.)  Much of it is readable, but even in 1-20, some
nonsensical line endings are still visible.

**Comment by cmahte** [comment]
Re: q0 -

q = poetry line centered in row of text (typically an italic row of text
centered in the column.) Depending on publishing decisions, sometimes this
is block centered, not each row independently centered.
q0 = poetry line starting the first row at the margin, then indenting by
1.5 units every text row after this.
q1 = poetry line starting the first row of text indented by 1 unit, then
indenting 2 or 2.5 units every row after that.

You'll find all of these are used in many translations and other works.
Because the CPDV presents  Lamentations as a dialog (like a play script
with each speaker mentioned with colons), the semanticly correct way to set
that is each row of text starts at the margin, but is then indented on
subsequent rows.  In PSFM, the best fit to acheive this particular
appearance is q0.

In the USFM specification, USFM tags with # hashes allow a single, optional
digit. Lower numbers indicate bigger or more space, and they go to null:
(null "", 0,1,2,3,4,5,6,7,8,9) are valid ways to append any tag that
includes a # hash in the USFM specification.)

For presentation tags, where the hash indicates a horizontal shift, higher
numbers indicate the shift from the margin level. In USFM, null "" and 1
are equivalent. In PSFM these are 2 discrete values set 2 steps apart.

For titling tags, level 4 indicates a text size roughly equivalent to body
text.  In USFM, null "" and 1 are equivalent. In PSFM these are 2 discrete
values set 2 steps apart.

In PSFM I include \toc to have a hash in the USFM specification, even
though it does not. Formally, \toc is only explicitly toc1, toc2, toc3.
However, the null form, "toc (null)" is an* obsolete *form of a file or
periph tag, and will cause the entire project to be rejected. So, toc0 =
centered rows in the table of contents to define separations  or groups
like "Old Testament", "New Testament", etc.

But, by always designing to this plan, it remains valid USFM, but also
allows quicker production of books about the bible, since stylesheets that
handle scripture well are ready to also handle deeper body lists, more
section titles, etc. like  you see in textbooks.

**Comment by DavidHaslam** [comment]
What on earth is PSFM ?  Where is it documented ?

If there are useful constructs in PSFM that USFM lacks, why not just propose them to ICAP ?
